### ISSUE TITLE
Console errors about MainWindow missing a 'present' attribute

### ISSUE THREAD

**Issue by aperezdc** [aperezdc/revolt#18]
When clicking on the status icon:

```
Traceback (most recent call last):
  File "/home/aperez/devel/revolt/revolt", line 100, in __on_left_click
    self.__app.show()
  File "/home/aperez/devel/revolt/revolt", line 389, in show
    self.window.present()
AttributeError: 'MainWindow' object has no attribute 'present'
Traceback (most recent call last):
  File "/home/aperez/devel/revolt/revolt", line 100, in __on_left_click
    self.__app.show()
  File "/home/aperez/devel/revolt/revolt", line 389, in show
    self.window.present()
AttributeError: 'MainWindow' object has no attribute 'present'
```

**Comment by aperezdc** [comment]
Ideally, our application class should inherit from `Gtk.Application`, and our `MainWindow` class should inherit from `Gtk.ApplicationWindow`. That way we can call the inherited `MainWindow.present()` directly, which makes more sense. I'll do the refactoring, but if it would take much time, I'll see to pushing a quick fix for this issue first.
